### ISSUE TITLE
Cannot push 3D model to KiCad

### ISSUE THREAD

**Issue by bstanwell-acs** [easyw/kicadStepUpMod#135]
It doesn't happen for every part, but it seems to fail when I attempt to push these connectors back to kicad

```
11:21:41  Running the Python command 'ksuToolsPushMoved' failed:
Traceback (most recent call last):
  File "C:\Users\benjamin stanwell\AppData\Roaming\FreeCAD\Mod\kicadStepUpMod\.\kicadStepUpCMD.py", line 1260, in Activated
    kicadStepUptools.PushMoved()
  File "C:\Users\benjamin stanwell\AppData\Roaming\FreeCAD\Mod\kicadStepUpMod\.\kicadStepUptools.py", line 15451, in PushMoved
    content = push3D2pcb(s,content,ts)
  File "C:\Users\benjamin stanwell\AppData\Roaming\FreeCAD\Mod\kicadStepUpMod\.\kicadStepUptools.py", line 20663, in push3D2pcb
    old_val_angle = (float(val_values[2]))

could not convert string to float: 'unlocked'loading from C:/Users/benjamin stanwell/OneDrive - Austindo/Documents/GitHub/Overhead-LED-Panel/ControlBoard/ledPanelReplacement.kicad_pcb
```

**Comment by easyw** [comment]
@bstanwell-acs 
would you mind to upload a minimal board that is producing this error?
Are you on kv5 or kv6 or kv6.99?
Which is your footprint lock property?
