### ISSUE TITLE
Failed to create face from wire

### ISSUE THREAD

**Issue by Youras** [easyw/kicadStepUpMod#180]
Hello, 

I want to load the open hardware KiCad project:
https://github.com/AnaviTechnology/anavi-miracle-uhat

But I receive the following logs:

```
18:08:49  kicad StepUp version 10.8.7
18:08:49  tolerance on vertex applied
18:08:49  opening C:/Users/younes/anavi-miracle-uhat/anavi-miracle-uhat.kicad_pcb
18:08:49  my file path C:\Users\younes\anavi-miracle-uhat
18:08:49  opening Transaction 'opening_kicad'
18:08:49  grid origin not set
using default top left corner
18:08:49  PCB Loader 
18:08:49  pcb thickness 1.6mm
18:08:49  kicad_pcb version 20211014
18:08:49  parsing
18:08:49  8 edge segments
18:08:49  aux or grid origin not found
18:08:49  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\younes\AppData\Roaming\FreeCAD\Mod\kicadStepUpMod\.\kicadStepUptools.py", line 1747, in open
    onLoadBoard(filename,None,insert)
  File "C:\Users\younes\AppData\Roaming\FreeCAD\Mod\kicadStepUpMod\.\kicadStepUptools.py", line 6699, in onLoadBoard
    modules,nsk = DrawPCB(mypcb,SketchLayer,override_pcb,keep_pcb_sketch)
  File "C:\Users\younes\AppData\Roaming\FreeCAD\Mod\kicadStepUpMod\.\kicadStepUptools.py", line 12128, in DrawPCB
    circle1=Part.Face(circle1)
<class 'Part.OCCError'>: Failed to create face from wire
```

How can this be solved?

**Comment by easyw** [comment]
@Youras 
your board has two circles with 0 radius in Edge.Cuts at:
```
  (gr_circle (center 211.0011 101.5036) (end 211.0011 101.5036)
    (stroke (width 0.1) (type solid)) (fill none) (layer "Edge.Cuts") (tstamp 1fa508ef-df83-4c99-846b-9acf535b3ad9))
  (gr_circle (center 152.0011 101.5036) (end 152.0011 101.5036)
    (stroke (width 0.1) (type solid)) (fill none) (layer "Edge.Cuts") (tstamp 399fc36a-ed5d-44b5-82f7-c6f83d9acc14))
```

delete those and kSU will not fail
(kicad DRC should be pointing on this issue)
