### ISSUE TITLE
Error when importing PCB: "Trouble with nesting of brackets"

### ISSUE THREAD

**Issue by salfter** [easyw/kicadStepUpMod#185]
I checked out https://github.com/adafruit/Adafruit-Feather-M4-Express-PCB, imported it into KiCad 7.0.7, and added 3D models to the imported components so I could make an STL model for use in OpenSCAD.  Upon trying to import the PCB into FreeCAD, though, I get the following:

```
opening C:/Users/salfter/Documents/PlatformIO/Projects/FeatherM4Express_PanicButton/hw/Adafruit-Feather-M4-Express-PCB/Adafruit Feather M4 Express.kicad_pcb
12:26:14  my file path C:\Users\salfter\Documents\PlatformIO\Projects\FeatherM4Express_PanicButton\hw\Adafruit-Feather-M4-Express-PCB
12:26:14  opening Transaction 'opening_kicad'
12:26:14  Running the Python command 'ksuToolsOpenBoard' failed:
Traceback (most recent call last):
  File "C:\Users\salfter\AppData\Roaming\FreeCAD\Mod\kicadStepUpMod\.\kicadStepUpCMD.py", line 1205, in Activated
    kicadStepUptools.onLoadBoard()
  File "C:\Users\salfter\AppData\Roaming\FreeCAD\Mod\kicadStepUpMod\.\kicadStepUptools.py", line 6655, in onLoadBoard
    mypcb = KicadPCB.load(name) #test parser
  File "C:\Users\salfter\AppData\Roaming\FreeCAD\Mod\kicadStepUpMod\.\fcad_parser\kicad_pcb.py", line 101, in load
    return KicadPCB(parseSexp(f.read().decode("UTF-8"), quote_no_parse)) # maui
  File "C:\Users\salfter\AppData\Roaming\FreeCAD\Mod\kicadStepUpMod\.\fcad_parser\sexp_parser\sexp_parser.py", line 798, in parseSexp
    assert stack, "Trouble with nesting of brackets"

Trouble with nesting of brackets
```

The file that's causing the problem is attached.

[Adafruit Feather M4 Express.zip](https://github.com/easyw/kicadStepUpMod/files/12742615/Adafruit.Feather.M4.Express.zip)

**Comment by easyw** [comment]
it seems there is an issue in "R8" which has a value of "10K\"
the extra character is breaking the parser.
Remove the extra "\" and t
![R8-error](https://github.com/easyw/kicadStepUpMod/assets/3032347/d372c0e4-dc1c-4deb-a2b7-385f653628f5)
he board should be loaded in FC correctly.
