### ISSUE TITLE
Plugin crashes when no ShapeColor 

### ISSUE THREAD

**Issue by phodina** [easyw/kicadStepUpMod#224]
Hi,
I've recently wanted to export WRL model to Kicad of this [component](https://gitlab.com/phodina/kicad-packages3D-source/-/blob/nintendo/Connector.3dshapes/Nintendo_Wii_Peripheral_6Pin_Socket_Horizontal.FCStd?ref_type=heads).

However I encountered some issue and don't know how to fix it. The plugin during export crashes as the property `ShapeColor` is not set.

```
18:22:54  Running the Python command 'ksuToolsExportModel' failed:
Traceback (most recent call last):
  File "/home/cylon2p0/.local/share/FreeCAD/Mod/kicadStepUpMod/./kicadStepUpCMD.py", line 1292, in Activated
    routineScaleVRML()
  File "/home/cylon2p0/.local/share/FreeCAD/Mod/kicadStepUpMod/./kicadStepUptools.py", line 7571, in routineScaleVRML
    lbl=go_export(fullFilePathName)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cylon2p0/.local/share/FreeCAD/Mod/kicadStepUpMod/./kicadStepUptools.py", line 2717, in go_export
    export(objs, fPathName, 0.3937, lbl)
  File "/home/cylon2p0/.local/share/FreeCAD/Mod/kicadStepUpMod/./kicadStepUptools.py", line 2331, in export
    color.append(FreeCADGui.ActiveDocument.getObject(obj.Name).ShapeColor)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

'Gui.ViewProviderDocumentObject' object has no attribute 'ShapeColor'KiCadStepUpWB.Deactivated()
```

**Comment by taintedkernel** [comment]
I encountered this as well.  Is there any workaround possible?

I tried hacking around the referenced Python file, but wasn't able to permanently fix it.  I'm pretty unfamiliar with FreeCAD and especially it's internals, so I don't have much expertise to rely on.
