### ISSUE TITLE
Crash when importing footprint containing custom pad with number box primitive

### ISSUE THREAD

**Issue by Swij** [easyw/kicadStepUpMod#227]
I encounter a crash when loading a footprint that contains a custom pad with a number box primitve.

If the number box primitive is removed, the footprint is loaded without any issues.

FreeCAD 0.21.2 installed with Flatpak. Operating system is Debian Testing.

```
12:02:50  kicad StepUp version 12.2.6
12:02:50  tolerance on vertex applied
12:02:50  kicad_parser_version 2.3.3
12:02:50  footprints version: 1.1.2
12:03:04  /home/redacted/example.pretty/example.kicad_mod
12:03:04  cannot find kicad_common
12:03:04  kicad version=20211014
12:03:04  kicad v5 stack missing
12:03:04  file removed
12:03:04  making holes
12:03:04  making holes...
12:03:04    pad holes: 0, skipped: 0
12:03:04    oval holes: 0
12:03:04    via holes: 0, skipped: 0
12:03:04    total holes added: 0
12:03:04  holes done
12:03:04  making Top Pads
12:03:04  making pads...
12:03:04    checking edge cuts
12:03:04  Unknown primitive gr_bbox in custom pad
12:03:04  Traceback (most recent call last):
12:03:04    File "/home/redacted/.var/app/org.freecadweb.FreeCAD/data/FreeCAD/Mod/kicadStepUpMod/./kicadStepUptools.py", line 14727, in onLoadFootprint_click
12:03:04      fps.addfootprint()
12:03:04    File "/home/redacted/.var/app/org.freecadweb.FreeCAD/data/FreeCAD/Mod/kicadStepUpMod/./fps.py", line 569, in addfootprint
12:03:04      topP=pcb.makePads(shape_type='wire',thickness=deltaz,holes=False,fit_arcs=True)  #solid',thickness=deltaz,holes=True,fit_arcs=True)
12:03:04           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12:03:04    File "/home/redacted/.var/app/org.freecadweb.FreeCAD/data/FreeCAD/Mod/kicadStepUpMod/./kicad_parser.py", line 1843, in makePads
12:03:04      w = Part.makeCompound([w,wp])
12:03:04          ^^^^^^^^^^^^^^^^^^^^^^^^^
12:03:04  TypeError: expect shape in sequence
```

[example_footprint.zip](https://github.com/user-attachments/files/16624041/example_footprint.zip)

Screenshot from KiCad documentation about vustom pad number box primitives:
![Screenshot from 2024-08-15 12-04-27](https://github.com/user-attachments/assets/04e69110-261e-488f-a280-5a0e74a23d3b)

**Comment by easyw** [comment]
@Swij 
thanks for the detailed issue...
it shold now fixed w/ commit https://github.com/easyw/kicadStepUpMod/commit/8cc48441818b3f52f75942f02091b16fe2350a46
