### ISSUE TITLE
cannot load KiCAD PCB

### ISSUE THREAD

**Issue by mreed102** [easyw/kicadStepUpMod#45]
**FreeCAD version**
```
OS: macOS 10.14
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16146 (Git)
Build type: Release
Branch: (HEAD detached at 0.18.4)
Hash: 980bf9060e28555fecd9e3462f68ca74007b70f8
Python version: 3.6.7
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)
```

**KiCAD version**
```
Application: Pcbnew
Version: (5.1.5-0-10_14), release build
Libraries:
    wxWidgets 3.0.4
    libcurl/7.54.0 LibreSSL/2.6.5 zlib/1.2.11 nghttp2/1.24.1
Platform: Mac OS X (Darwin 18.7.0 x86_64), 64 bit, Little endian, wxMac
Build Info:
    wxWidgets: 3.0.4 (wchar_t,STL containers,compatible with 2.8)
    Boost: 1.69.0
    OpenCASCADE Community Edition: 6.9.1
    Curl: 7.54.0
    Compiler: Clang 9.0.0 with C++ ABI 1002

Build settings:
    USE_WX_GRAPHICS_CONTEXT=ON
    USE_WX_OVERLAY=ON
    KICAD_SCRIPTING=ON
    KICAD_SCRIPTING_MODULES=ON
    KICAD_SCRIPTING_PYTHON3=OFF
    KICAD_SCRIPTING_WXPYTHON=ON
    KICAD_SCRIPTING_WXPYTHON_PHOENIX=OFF
    KICAD_SCRIPTING_ACTION_MENU=ON
    BUILD_GITHUB_PLUGIN=ON
    KICAD_USE_OCE=ON
    KICAD_USE_OCC=OFF
    KICAD_SPICE=ON
```

Steps to reproduce:
1) install KiCAD stepup mod to Freecad using Addon Manager
2) select kicadstepup as the workbench
3) hit the icon for "load kicad PCB board and parts"
4) finder browser, navigate to my kicad project
5) the .kicad_pcb file is the only filetype that can be selected (others are grayed out)
6) select the one and only .kicad_pcb file
7) receive error msg:
```
Running the Python command 'ksuToolsOpenBoard' failed:
Traceback (most recent call last):
  File "/Users/redactedFella/Library/Preferences/FreeCAD/Mod/kicadStepUpMod/kicadStepUpCMD.py", line 656, in Activated
    kicadStepUptools.onLoadBoard()
  File "/Users/redactedFella/Library/Preferences/FreeCAD/Mod/kicadStepUpMod/kicadStepUptools.py", line 7668, in onLoadBoard
    if hasattr(mypcb.setup, 'grid_origin'):
  File "/Users/redactedFella/Library/Preferences/FreeCAD/Mod/kicadStepUpMod/kicadStepUptools.py", line 936, in __getattr__
    raise AttributeError('{}: key "{}" not found'.format(self._line,name))

1: key "setup" not found
```

**Comment by mreed102** [comment]
Sorry for the noise.  User error.  Fixed either one or both of these actions:

- do the kicadsteupmod setup (for Mac, set KISYS3DMOD to /Library/Application Support/kicad/modules/packages3d)
- set an origin for your board in KiCAD PCB.
