### ISSUE TITLE
Cannot import tracks from zone with kicad_pcb having "(layers *.Cu)"

### ISSUE THREAD

**Issue by paulreimer** [easyw/kicadStepUpMod#6]
With this in my kicad_pcbnew:
```
(zone (net 0) (net_name "") (layers *.Cu) (tstamp 0) (hatch edge 0.508)
...
```

I get this error about halfway through importing tracks:

```
  making zones...
Running the Python command 'ksuToolsAddTracks' failed:
Traceback (most recent call last):
  File "/Library/Preferences/FreeCAD/Mod/kicadStepUpMod/kicadStepUpCMD.py", line 2454, in Activated
    tracks.addtracks()
  File "./Library/Preferences/FreeCAD/Mod/kicadStepUpMod/tracks.py", line 163, in addtracks
    pcb.makeCopper(holes=True, minSize=minSizeDrill)
  File "./Library/Preferences/FreeCAD/Mod/kicadStepUpMod/kicad.py", line 1338, in makeCopper
    thickness=thickness)
  File "./Library/Preferences/FreeCAD/Mod/kicadStepUpMod/kicad.py", line 1227, in makeZones
    if z.layer != self.layer:
  File "./Library/Preferences/FreeCAD/Mod/kicadStepUpMod/kicadStepUptools.py", line 826, in __getattr__
    raise AttributeError('{}: key "{}" not found'.format(self._line,name))

5607: key "layer" not found
```

However if I change edit the kicad_pcbnew file manually and change `(layers *.Cu)` to `(layer F.Cu)` it does seem to work (my other zones are only on a single layer, I guess... I think I normally duplicate them but maybe I selected multiple layers one time?)

**Comment by easyw** [comment]
Hi,
which version of kicad are you using?
I cannot find a way to assign a fill zone to "All Copper Layer"..
With which menu can you assign it?

**Comment by easyw** [comment]
Hi @paulreimer 
I should have fixed the parsing also for keepout regions..
please have a try with the latest update ...

**Comment by easyw** [comment]
I'm going to close it as solved.
Please feel free to reach open it in case you still have issues.
