### ISSUE TITLE
`ksu Export 3D Model` error `'Gui.ViewProviderLink' object has no attribute 'ShapeColor'`

### ISSUE THREAD

**Issue by s-light** [easyw/kicadStepUpMod#90]
if your model contains links - in my case a [`Array`](https://wiki.freecadweb.org/Draft_LinkArray/en) - the `ksu Export 3D Model` fails with
`'Gui.ViewProviderLink' object has no attribute 'ShapeColor'`

```
21:52:34  routine Scale to VRML 1/2.54
21:52:34  exporting
21:52:34  /home/stefan/mydata/parts_info/VISHAY/VISHAY_Panhead_4PIN__test.FCStd
21:52:34  Running the Python command 'ksuToolsExportModel' failed:
Traceback (most recent call last):
  File "/home/stefan/mydata/freecad/.FreeCAD/Mod/kicadStepUpMod/kicadStepUpCMD.py", line 878, in Activated
    routineScaleVRML()
  File "/home/stefan/mydata/freecad/.FreeCAD/Mod/kicadStepUpMod/kicadStepUptools.py", line 8421, in routineScaleVRML
    lbl=go_export(fullFilePathName)
  File "/home/stefan/mydata/freecad/.FreeCAD/Mod/kicadStepUpMod/kicadStepUptools.py", line 3517, in go_export
    check_AP()
  File "/home/stefan/mydata/freecad/.FreeCAD/Mod/kicadStepUpMod/kicadStepUptools.py", line 3222, in check_AP
    recurse_node(obj,obj.Placement, sc_list)
  File "/home/stefan/mydata/freecad/.FreeCAD/Mod/kicadStepUpMod/kicadStepUptools.py", line 2776, in recurse_node
    simple_cpy_plc(o,plcm)
  File "/home/stefan/mydata/freecad/.FreeCAD/Mod/kicadStepUpMod/kicadStepUptools.py", line 2733, in simple_cpy_plc
    FreeCADGui.ActiveDocument.ActiveObject.ShapeColor=FreeCADGui.ActiveDocument.getObject(obj.Name).ShapeColor
```

**Comment by easyw** [comment]
> if your model contains links - in my case a [`Array`](https://wiki.freecadweb.org/Draft_LinkArray/en) - the `ksu Export 3D Model` fails with
> `'Gui.ViewProviderLink' object has no attribute 'ShapeColor'`

1) please provide a sample file...
2) moreover if you use the button to make a compound or an unioned copy (both in ksu wb) your probleb should be solved
