### ISSUE TITLE
Cant export footprint

### ISSUE THREAD

**Issue by myhrmans** [easyw/kicadStepUpMod#97]
Hi there,
first time testing this mod so might be user error but I keep getting the following error from trying to export a simple footprint:
`08:31:51  ['Value ']
08:31:55  exporting new footprint
08:31:55  saving to C:/Users/myhrmans/repos/kicad-libraries/footprints/NCSR170F.pretty/test.kicad_mod
08:31:55  Group
08:31:55  Sketch
08:31:55  Sketch001
08:31:55  Text
08:31:55  Text001
08:31:55  2d closed path
08:31:55  2d closed path
08:31:55  horizontal
08:31:55  Running the Python command 'ksuToolsFootprintGen' failed:
Traceback (most recent call last):
  File "C:\Users\myhrmans\AppData\Roaming\FreeCAD\Mod\kicadStepUpMod\kicadStepUpCMD.py", line 2112, in Activated
    kicadStepUptools.PushFootprint()
  File "C:\Users\myhrmans\AppData\Roaming\FreeCAD\Mod\kicadStepUpMod\kicadStepUptools.py", line 16198, in PushFootprint
    export_footprint(name)
  File "C:\Users\myhrmans\AppData\Roaming\FreeCAD\Mod\kicadStepUpMod\kicadStepUptools.py", line 16863, in export_footprint
    drl_found=collect_drl(pth_ordered)
  File "C:\Users\myhrmans\AppData\Roaming\FreeCAD\Mod\kicadStepUpMod\kicadStepUptools.py", line 17607, in collect_drl
    px=(p[0][10].x+p[2][11].x)/2;py=(p[0][11].y+p[2][11].y)/2;

list index out of range`

![image](https://user-images.githubusercontent.com/14261388/136743587-59d2e90a-80a0-4e2c-8fc3-087b27d0f318.png)

I think I have named the layers correct but can't tell, and here is the footprint:

![image](https://user-images.githubusercontent.com/14261388/136743659-8832dfe0-1694-4c43-b380-4926eca0ee7c.png)

Link to the step file: http://www.nichia.co.jp/specification/cad/KSE080226A.step

Thanks!

**Comment by easyw** [comment]
Hi @myhrmans 
for those pads you need to create Pads_Poly sketches
[Uploading ncsx170f-files.zip…]()
s
